# GitHub Actions for Dokploy Deployment
name: Deploy to Dokploy

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests (if you have them)
        run: npm test -- --watch=false --browsers=ChromeHeadless || true

      - name: Build application
        run: npm run build

      - name: Deploy to Dokploy
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          echo "Dokploy will handle deployment via webhook"
          # Dokploy webhook will be triggered automatically
          # No additional action needed if using Dokploy's GitHub integration
